### ISSUE TITLE
license

### ISSUE THREAD

**Issue by alephpi** [HowardZorn/kage-engine#1]
Hi, I'm forking your work and I hope you could add a license to it. I guess it should be GPL-v3 since the original KAGE-engine is so.

**Comment by HowardZorn** [comment]
Hello alephpi!

I am happy to receive your issue about the license of my repo. GPL-v3 is exactly the licence of this repo. I omitted it when I uploaded my code. Thanks for reminding me. I will fix it ASAP.

Fw[a]rd.

**Comment by HowardZorn** [comment]
Close #1, as it is fixed.
